# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.define:"ubuntu-1804-srv" do |cfgm|
		cfgm.vm.box = "peru/ubuntu-18.04-server-amd64"
 		cfgm.vm.box_version = "20190801.01"
		cfgm.vm.host_name = "ubuntu-1804-srv"
		cfgm.vm.network "public_network", ip: "192.168.1.100", bridge: "enp0s31f6"
		cfgm.vm.provision "shell", path: "install-docker.sh"

		cfgm.vm.provider:virtualbox do |vb|
			vb.name = "ubuntu-1804-srv"
			vb.customize ["modifyvm", :id, "--cpus", 4]
			vb.customize ["modifyvm", :id, "--memory", 4096]
			vb.gui = false
		end
	end

	config.vm.define:"docker-registry" do |cfgn|
		cfgn.vm.box = "peru/ubuntu-18.04-server-amd64"
 		cfgn.vm.box_version = "20190801.01"
		cfgn.vm.host_name = "docker-registry"
		cfgn.vm.network "public_network", ip: "192.168.1.101", bridge: "enp0s31f6"
		cfgn.vm.provision "shell", path: "install-docker.sh"

		cfgn.vm.provider:virtualbox do |vb|
			vb.name = "docker-registry"
			vb.customize ["modifyvm", :id, "--cpus", 4]
			vb.customize ["modifyvm", :id, "--memory", 4096]
			vb.gui = false
		end
	end


end
